version: '3.7'

services:
  
  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis:/data
    networks:
      - backend
    logging:
      driver: none

  mongo:
    image: mongo:4.1
    restart: unless-stopped
    volumes:
      - mongodb:/data/db
    networks:
      - backend
    environment:
      MONGO_INITDB_ROOT_USERNAME: noworry
      MONGO_INITDB_ROOT_PASSWORD: itsalocalapp
    command: --quiet --logpath /dev/null 
    logging:
      driver: none

  server:
    build: ./server
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MONGODB_URI: "mongodb://noworry:itsalocalapp@mongo"
      REDIS_HOST: "redis"
      ROUTE_SRC: "./dist/routes/"
    volumes:
      - /run/udev:/run/udev:ro
      - /dev:/dev
    privileged: true
    depends_on:
      - mongo
      - redis
    networks:
      - backend
    
  webapp:
    build: ./webapp
    restart: unless-stopped
    environment:
      API_URL: "http://localhost:$PORT"
    ports:
      - $PORT:80
    depends_on:
      - server
    networks:
      - backend

networks:
  backend:

volumes:
  mongodb:
  redis: