version: "3.7"

services:

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis:/data
    networks:
      - backend
    logging:
      driver: none

  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - mongodb:/data/db
    networks:
      - backend
    env_file: ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: noworry
      MONGO_INITDB_ROOT_PASSWORD: itsalocalapp
    command: --quiet --logpath /dev/null 
    logging:
      driver: none

  server:
    build: .
    restart: unless-stopped
    env_file: ./.env
    environment:
      MONGODB_URI: "mongodb://noworry:itsalocalapp@mongo"
      REDIS_HOST: "redis"
      ROUTE_SRC: "./dist/routes/"
    ports:
      - $API_PORT:$API_PORT
    depends_on:
      - mongo
      - redis
    networks:
      - backend

networks:
  backend:

volumes:
  mongodb:
  redis: