name: "[Prod]BuildDockerWebappImage"

on:
  push:
    branches:
      - stagging

env:
  REGISTRY_IMAGE: nicojqn/aquasensor-webapp

jobs:
  docker:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '#docs') }}
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./webapp/.
          push: true
          tags: ${{ env.REGISTRY_IMAGE }}:staging
